on:
  push:
    branches:
      - main
  pull_request:

name: fmt,lint,check,build
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v29

      - name: Flake checks
        run: nix flake check

      - name: baywatch - check build test clippy
        run: nix build
