on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing /

name: publish
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24

      - name: publish to crates.io
        run: nix develop --command -- cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
